### ISSUE TITLE
Filter icon does not do anything?

### ISSUE THREAD

**Issue by reswob10** [ericmccullough/r2d2#20]
Is the filter icon supposed to show a drop down or some other window?  

I'm using FF from Linux (ubuntu)

**Comment by ericmccullough** [comment]
I just noticed it doesn't do anything on the Layer 2 Sweeper Service home page.  I will hide it for now.

**Comment by ericmccullough** [comment]
Changed title of l2s2 top level so it will not display a non-functional filter button.
